### PR TITLE
Put correct nix-env command in README.md

### PR DESCRIPTION
**Pull request by kutyel**
Hi, I stumbled with this yesterday when trying this project out, thankfully @turboMaCk helped me out to install it correctly and also reminded me that a new version with the `uglify-js` fix needs to be published, thanks for this project! 😉

### CODE REVIEW

**Comment by turboMaCk** [comment]
@domenkozar if you want I can update nixpkgs to point to master but it might be better to release new version including the tag in git etc.

**Comment by domenkozar** [comment]
Thank you!

How come that existing the instructions don't work?

**Comment by turboMaCk** [comment]
There are two ways to install stuff via `nix-env`

1. Install by derivation name:

```
nix-env -i elm2nix
```

This will work becuse name is `elm2nix`

2. Install by attribute

```
nix-env -iA nixos.elm2nix
```
or
```
nix-env -iA nixpkgs.elm2nix
```

This also works becaus there is `elm2nix` attribute in `nixos/nixpkgs`.

However

```
nix-env -iA elm2nix
```
will fail because there is no channel named `elm2nix`.

```
error: attribute 'elm2nix' in selection path 'elm2nix' not found
```

**Comment by domenkozar** [comment]
I've forgot how channels work :)

**Comment by turboMaCk** [comment]
Frankly I made same mistake several times this year as I'm pushing folks to try nix. I myself use quite simple & quite monolithic approach of putting almost everything into my nixos config so I rarely use `nix-env`. So I knew right away what's up only because I made the same mistake myself. Maybe this can can make a list of special cases for improved error messages? If we would look that no commonly used name is present in attribute path we can print nicer message like "are you sure you don't forget to prefix by channel" type of message.

**Comment by domenkozar** [comment]
I agree, I'm gathering evidence why channels should be avoided in https://github.com/nix-dot-dev/nix.dev/issues/16#issuecomment-713701415

**Pull request merged**
